<?php
/** @var \Ewave\EventGenerateReport\Block\Adminhtml\Club\Event $block */
?>

<div class="reports-content">
    <?php echo $block->getChildHtml('grid.filter.form') ?>
</div>

<?php echo $block->getGridHtml() ?>

<script>
    require([
        'jquery',
        'mage/backend/validation',
        "prototype"
    ], function (jQuery) {

        function initEventOptions(clubId) {
            var clubs = <?= $block->getClubIdEvents()?>;
            var club = clubs[clubId];
            var $eventSelect = jQuery('#event_report_event_id');
            var options = '';
            for (var eventId in club) {
                var eventName = club[eventId];
                options += '<option value="' + eventId + '">' + eventName + '</option>';
            }
            $eventSelect.html(options);
        }

        window.initEventOptions = initEventOptions;

//<![CDATA[
        jQuery('#filter_form').mage('validation', {errorClass: 'mage-error'});
        function filterFormSubmit() {
            var filters = $$('#filter_form input', '#filter_form select');
            var elements = [];
            for (var i in filters) {
                if (filters[i].value && filters[i].value.length && !filters[i].disabled) elements.push(filters[i]);
            }
            if (jQuery('#filter_form').valid()) {
                setLocation('<?php /* @escapeNotVerified */ echo $block->getFilterUrl(
                    ); ?>filter/' + Base64.encode(Form.serializeElements(elements)) + '/');
            }
        }

//]]>
        window.filterFormSubmit = filterFormSubmit;
    });
</script>
